version: "3.9"

services:
  database:
    image: postgres:13
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./:/app/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - product-nw

  product-service:
    command: java -jar target/ProductMicroService-0.0.1-SNAPSHOT.jar
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - database
    volumes:
      - ./:/app/app
    links:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/postgres
      - SPRING_RABBITMQ_HOST=rabbitmq-container
      - SPRING_RABBITMQ_PORT=5672
    networks:
        - product-nw
        - service-nw

networks:
  product-nw:
    name: product-nw
  service-nw:
    name: service-nw
    external: true

